nodes:
- input.visual:
    source: C:\Users\Admin\Desktop\cam8
- model.mask_rcnn:
    model_type: r50-fpn
    detect: [2, 5, 7]   # car, bus, truck
    iou_threshold: 0.5
    score_threshold: 0.5
    mask_threshold: 0.5
# - draw.bbox:
#     show_labels: True
- output.csv_writer:
    stats_to_track: ["filename", "bboxes", "bbox_labels"]
    file_path: C:\Users\Admin\Desktop\cam8\annotations.csv
    logging_interval: 0
# - output.media_writer:
#     output_dir: C:\Users\Admin\Desktop\cam8